//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categories
    {
        public Categories()
        {
            this.Produits = new HashSet<Produits>();
        }
    
        public int IdCategorie { get; set; }
        public string Libelle { get; set; }
        public int IdModele { get; set; }
        public Nullable<long> IdCarburant { get; set; }
        public Nullable<short> PuissanceReelle { get; set; }
    
        public virtual ICollection<Produits> Produits { get; set; }
    }
}
