//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produits
    {
        public Produits()
        {
            this.Photos = new HashSet<Photos>();
        }
    
        public int IdProduit { get; set; }
        public string Couleur { get; set; }
        public string Description { get; set; }
        public Nullable<int> IdAcheteur { get; set; }
        public Nullable<int> IdVendeur { get; set; }
        public Nullable<int> IdAdresse { get; set; }
        public int Prix { get; set; }
        public int IdCategorie { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual ICollection<Photos> Photos { get; set; }
    }
}
