//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adress
    {
        public Adress()
        {
            this.Utilisateurs = new HashSet<Utilisateur>();
        }
    
        public int IdAdresse { get; set; }
        public string Ligne1 { get; set; }
        public string Ligne2 { get; set; }
        public string Ligne3 { get; set; }
        public string CodePostal { get; set; }
        public string CodeINSEE { get; set; }
    
        public virtual ZipCode ZipCode { get; set; }
        public virtual ICollection<Utilisateur> Utilisateurs { get; set; }
    }
}
