//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.SousCategories = new HashSet<SousCategory>();
        }
    
        public int IdCategorie { get; set; }
        public string Libelle { get; set; }
        public string Photo { get; set; }
    
        public virtual ICollection<SousCategory> SousCategories { get; set; }
    }
}
