//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commandes
    {
        public Commandes()
        {
            this.Commandes_details = new HashSet<Commandes_details>();
        }
    
        public int IdCommande { get; set; }
        public Nullable<int> IdAcheteur { get; set; }
        public Nullable<int> EtatCommande { get; set; }
        public Nullable<System.DateTime> DateCommande { get; set; }
        public Nullable<System.DateTime> DateLivraison { get; set; }
        public Nullable<int> IdAdresse { get; set; }
    
        public virtual ICollection<Commandes_details> Commandes_details { get; set; }
        public virtual Utilisateurs Utilisateurs { get; set; }
        public virtual StatusCommande StatusCommande { get; set; }
    }
}
