//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departements
    {
        public Departements()
        {
            this.Villes = new HashSet<Villes>();
        }
    
        public string NumDep { get; set; }
        public string NumReg { get; set; }
        public string Nom { get; set; }
    
        public virtual RegionsFR RegionsFR { get; set; }
        public virtual ICollection<Villes> Villes { get; set; }
    }
}
