//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Identite
    {
        public Identite()
        {
            this.Utilisateurs = new HashSet<Utilisateur>();
        }
    
        public int IdIdentite { get; set; }
        public string Nom { get; set; }
        public string Prenom { get; set; }
        public string Identifiant { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
    
        public virtual Administrateur Administrateur { get; set; }
        public virtual ICollection<Utilisateur> Utilisateurs { get; set; }
    }
}
