//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Region
    {
        public Region()
        {
            this.Pays = new HashSet<Pay>();
        }
    
        public int idRegion { get; set; }
        public string name { get; set; }
        public int idContinent { get; set; }
    
        public virtual Continent Continent { get; set; }
        public virtual ICollection<Pay> Pays { get; set; }
    }
}
