//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ville
    {
        public Ville()
        {
            this.ZipCodes = new HashSet<ZipCode>();
        }
    
        public string CodeINSEE { get; set; }
        public string Commune { get; set; }
        public string Statut { get; set; }
        public Nullable<int> AltitudeMoyenne { get; set; }
        public Nullable<double> Superficie { get; set; }
        public Nullable<double> Population { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string CodeCommune { get; set; }
        public string CodeCanton { get; set; }
        public string CodeArrondissement { get; set; }
        public string NumDep { get; set; }
        public string Nom { get; set; }
        public string NomTri { get; set; }
        public string Prefixe { get; set; }
    
        public virtual Departement Departement { get; set; }
        public virtual ICollection<ZipCode> ZipCodes { get; set; }
    }
}
