//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZipCode
    {
        public ZipCode()
        {
            this.Adresses = new HashSet<Adress>();
        }
    
        public string CodePostal { get; set; }
        public string CodeINSEE { get; set; }
    
        public virtual ICollection<Adress> Adresses { get; set; }
        public virtual Ville Ville { get; set; }
    }
}
